name: build-release

on: push

jobs:
  fe:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          registry: docker.io
          username: sssomeshhh
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Setup Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Build Target
        uses: docker/build-push-action@v5.3.0
        with:
          builder: ${{ steps.setup_buildx.name }}
          context: .
          file: Dockerfile
          target: fe
          cache-from: |
            type=registry,ref=sssomeshhh/cache:rentify-fe
          cache-to: |
            type=registry,ref=sssomeshhh/cache:rentify-fe
          load: false
          push: true
          tags: |
            sssomeshhh/rentify:fe
            sssomeshhh/rentify:fe-${{ github.sha }}

  fs:
    runs-on: ubuntu-22.04
    needs:
      - fe
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          registry: docker.io
          username: sssomeshhh
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Setup Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Build Target
        uses: docker/build-push-action@v5.3.0
        with:
          builder: ${{ steps.setup_buildx.name }}
          context: .
          file: Dockerfile
          target: fs
          cache-from: |
            type=registry,ref=sssomeshhh/cache:rentify-fs
          cache-to: |
            type=registry,ref=sssomeshhh/cache:rentify-fs
          load: false
          push: true
          tags: |
            sssomeshhh/rentify:fs
            sssomeshhh/rentify:fs-${{ github.sha }}
